// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('@arco-design/web-vue')['Breadcrumb']
    ABreadcrumbItem: typeof import('@arco-design/web-vue')['BreadcrumbItem']
    AButton: typeof import('@arco-design/web-vue')['Button']
    AccessBtn: typeof import('./src/components/AccessBtn.vue')['default']
    AddModal: typeof import('./src/components/addModal.vue')['default']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
    ALink: typeof import('@arco-design/web-vue')['Link']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    AOption: typeof import('@arco-design/web-vue')['Option']
    ArrayList: typeof import('./src/components/charts/ArrayList.vue')['default']
    'ArrayList copy': typeof import('./src/components/charts/ArrayList copy.vue')['default']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu']
    Chart: typeof import('./src/components/chart.vue')['default']
    Editor: typeof import('./src/components/editor.vue')['default']
    EraseModal: typeof import('./src/components/EraseModal.vue')['default']
    InsertModal: typeof import('./src/components/InsertModal.vue')['default']
    'InsertModal copy': typeof import('./src/components/InsertModal copy.vue')['default']
    Linear: typeof import('./src/components/charts/Linear.vue')['default']
    LinkList: typeof import('./src/components/charts/LinkList.vue')['default']
    PushModal: typeof import('./src/components/PushModal.vue')['default']
    'PushModal copy': typeof import('./src/components/PushModal copy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
